from enum import StrEnum


class ReasonCode(StrEnum):
    FAVORABLE_MATCHUP = "FAVORABLE_MATCHUP"
    OPPONENT_CS_APPROACH = "OPPONENT_CS_APPROACH"
    ENEMY_JUNGLE_UNKNOWN = "ENEMY_JUNGLE_UNKNOWN"
    ENEMY_JUNGLE_CONFIRMED_FAR = "ENEMY_JUNGLE_CONFIRMED_FAR"
    SAFE_RETURN_PATH = "SAFE_RETURN_PATH"
    LOW_REVERSIBILITY = "LOW_REVERSIBILITY"
