'use strict';
const assert=require('node:assert/strict');
module.exports=async function({page,check,baseUrl,token}){
 const headers={Authorization:'Bearer '+token};
 const api=async(path,method='GET',data)=>{const r=await page.context().request.fetch(baseUrl+'/dev/v1'+path,{method,headers,...(data===undefined?{}:{data})});return {status:r.status(),body:await r.json()};};
 await page.click('#show-synthetic');
 if(await page.locator('#auth-panel').isVisible()){await page.fill('#token',token);await page.click('#login-form button');await page.waitForSelector('#workspace:visible');}
 const resource=(await api('/research','POST',{source_type:'raw_json',title:'승인 흐름 합성 출처',raw_text:JSON.stringify({review_fixture:Date.now()})})).body;
 await api('/research/'+resource.id+'/notes/overview','PUT',{note:{known:'합성 출처 검증',intention:'',alternative:'UNKNOWN',outcome:''},expected_revision:0});
 const rule={patch_range:'UNKNOWN',applicability:{champion:'UNKNOWN',role:'UNKNOWN',matchup:'UNKNOWN',level:'UNKNOWN',context:'UNKNOWN'},required_fields:['UNKNOWN'],claim:'승인용 합성 주장',mechanism:'합성 테스트',counterexamples:['UNKNOWN'],author:'테스트 작성자',limitations:['실경기 검증 아님']};
 const first=(await api('/knowledge/proposals','POST',{rule,source:{resource_id:resource.id,anchor:'overview',note_revision:1},rule_id:null,expected_version:null})).body;
 const path='/knowledge/proposals/'+first.rule_id;
 await page.click('#show-knowledge');
 await page.click('#k-list button[data-version-id="'+first.version+'"]');
 await page.waitForFunction(v=>kRecord&&kRecord.version===v,first.version);
 check('knowledge-review-controls-show-exact-selected-version',await page.locator('#k-review').isEnabled()&&await page.locator('#k-reject').isEnabled(),{selected_version:first.version});
 let decisions=0;const track=r=>{if(r.method()==='POST'&&r.url().endsWith('/decisions'))decisions++;};page.on('request',track);
 try{
  await page.evaluate(()=>{document.getElementById('k-review').click();document.getElementById('k-reject').dispatchEvent(new MouseEvent('click',{bubbles:true}));});
  assert.equal(decisions,0);assert.equal((await api(path)).body.version,first.version);
  check('knowledge-review-script-clicks-cannot-decide',decisions===0,{decision_requests:decisions});
  const denied=await api(path+'/decisions','POST',{selected_version:first.version,expected_version:first.version,decision:'REVIEWED',patch_range:'26.20',applicability:{champion:'애쉬',role:'원딜',matchup:'케이틀린',level:'1~3',context:'라인 진입'}});
  check('knowledge-review-api-automation-denied',denied.status===403&&denied.body.error_code==='USER_WEB_REVIEW_REQUIRED',{status:denied.status});
  await page.click('#k-review');
  await page.waitForFunction(()=>document.getElementById('k-notice').textContent.includes('미확인'));
  check('knowledge-review-unknown-scope-blocked-before-request',decisions===0,{decision_requests:decisions});
  const scope={patch:'26.20',champion:'애쉬',role:'원딜',matchup:'케이틀린 상대',level:'1~3',context:'아군 서포터와 라인 진입'};
  for(const [key,value] of Object.entries(scope))await page.fill('#k-'+key,value);
  page.once('dialog',d=>d.dismiss());await page.click('#k-review');
  check('knowledge-review-native-cancel-keeps-candidate',decisions===0&&(await api(path)).body.version===first.version,{decision_requests:decisions});
  page.once('dialog',d=>d.accept());const response=page.waitForResponse(r=>r.url().endsWith('/decisions')&&r.request().method()==='POST');await page.click('#k-review');const actual=await response,saved=await actual.json();
  await page.waitForFunction(v=>kRecord&&kRecord.version===v,saved.version);
  const old=(await api(path+'/versions/'+first.version)).body;
  check('knowledge-review-native-click-persists-reviewed-immutable-version',actual.status()===201&&saved.review_state==='REVIEWED'&&saved.supersedes===first.version&&saved.version!==first.version&&saved.review_decision.selected_version===first.version&&require('node:util').isDeepStrictEqual(saved.source_refs,first.source_refs)&&require('node:util').isDeepStrictEqual(old,first)&&!saved.coaching_enabled,{status:actual.status(),selected:first.version,saved:saved.version,state:saved.review_state});
  check('knowledge-review-label-and-list-reflect-reviewed', (await page.locator('#k-current').innerText()).includes('REVIEWED')&&(await page.locator('#k-list').innerText()).includes('REVIEWED'),{state:saved.review_state});
  await page.click('#k-list button[data-version-id="'+first.version+'"]');await page.waitForFunction(v=>kRecord&&kRecord.version===v,first.version);
  page.once('dialog',d=>d.accept());const rejectedResponse=page.waitForResponse(r=>r.url().endsWith('/decisions')&&r.request().method()==='POST');await page.click('#k-reject');const rejection=await rejectedResponse,rejected=await rejection.json();await page.waitForFunction(v=>kRecord&&kRecord.version===v,rejected.version);
  check('knowledge-review-historical-native-reject-binds-selected-and-latest',rejection.status()===201&&rejected.review_state==='REJECTED'&&rejected.review_decision.selected_version===first.version&&rejected.supersedes===saved.version&&rejected.patch_range==='UNKNOWN'&&!rejected.coaching_enabled,{selected:first.version,parent:saved.version,state:rejected.review_state});
  await page.reload();await page.waitForSelector('#workspace:visible');await page.click('#show-knowledge');await page.click('#k-list button[data-version-id="'+rejected.version+'"]');await page.waitForFunction(v=>kRecord&&kRecord.version===v,rejected.version);
  check('knowledge-review-reload-preserves-decision', (await page.locator('#k-current').innerText()).includes('REJECTED')&&require('node:util').isDeepStrictEqual((await api(path+'/versions/'+saved.version)).body,saved),{state:rejected.review_state});
  await page.fill('#k-claim','미저장 변경 승인 금지');await page.click('#k-review');await page.waitForFunction(()=>document.getElementById('k-notice').textContent.includes('저장'));
  check('knowledge-review-unsaved-claim-cannot-be-silently-reviewed',decisions===2&&(await api(path)).body.version===rejected.version,{decision_requests:decisions});
  page.once('dialog',d=>d.accept());await page.click('#k-new');
  let race=(await api('/knowledge/proposals','POST',{rule:{...rule,claim:'응답 소유권 합성 후보'},source:{resource_id:resource.id,anchor:'overview',note_revision:1},rule_id:null,expected_version:null})).body;
  await page.click('#k-refresh');await page.click('#k-list button[data-version-id="'+race.version+'"]');await page.waitForFunction(v=>kRecord&&kRecord.version===v,race.version);
  await page.fill('#k-claim','저장 후 직접 승인할 후보');
  const editResponse=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/knowledge/proposals'));
  await page.click('#k-save');race=await (await editResponse).json();await page.waitForFunction(v=>kRecord&&kRecord.version===v&&!kSaving,race.version);
  check('knowledge-review-controls-ready-after-native-candidate-save',await page.locator('#k-review').isEnabled()&&await page.locator('#k-reject').isEnabled(),{saved_version:race.version});
  for(const [key,value] of Object.entries(scope))await page.fill('#k-'+key,value);
  let release,committed;const gate=new Promise(resolve=>release=resolve),ready=new Promise(resolve=>committed=resolve);
  const cdp=await page.context().newCDPSession(page);
  await cdp.send('Fetch.enable',{patterns:[{urlPattern:'*/knowledge/proposals/'+race.rule_id+'/decisions',requestStage:'Response'}]});
  cdp.on('Fetch.requestPaused',async event=>{const response=await cdp.send('Fetch.getResponseBody',{requestId:event.requestId});const text=response.base64Encoded?Buffer.from(response.body,'base64').toString():response.body;committed({status:event.responseStatusCode,body:JSON.parse(text)});await gate;await cdp.send('Fetch.continueResponse',{requestId:event.requestId});});
  page.once('dialog',d=>d.accept());await page.click('#k-review');const held=await ready;
  page.once('dialog',d=>d.accept());await page.click('#k-new');await page.fill('#k-claim','늦은 승인 응답이 바꾸면 안 되는 초안');
  const delivered=page.waitForResponse(r=>r.url().endsWith('/'+race.rule_id+'/decisions'));release();await delivered;await cdp.send('Fetch.disable');await cdp.detach();await page.evaluate(()=>new Promise(resolve=>setTimeout(resolve,0)));
  check('knowledge-review-held-ack-cannot-replace-new-editor',held.status===201&&held.body.review_state==='REVIEWED'&&await page.evaluate(()=>kRecord===null&&kDirty&&document.getElementById('k-claim').value==='늦은 승인 응답이 바꾸면 안 되는 초안'),{status:held.status,state:held.body.review_state});
  const savedRead=await api('/knowledge/proposals/'+race.rule_id);
  check('knowledge-review-held-ack-keeps-actual-backend-decision',savedRead.body.version===held.body.version&&savedRead.body.review_decision.selected_version===race.version,{saved_version:savedRead.body.version});
 }finally{page.off('request',track);}
};
