'use strict';
// Actual browser + HTTP + SQLite. Held GET bodies come from route.fetch. The
// stale DELETE-owner scenarios explicitly gate native request dispatch before
// route.fetch so new anchor/resource previews exist before the real commit.
const crypto=require('node:crypto');
const fields=['known','intention','alternative','outcome'];
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
function canonical(value){if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}';return JSON.stringify(value);}
const equal=(a,b)=>canonical(a)===canonical(b);
function deferred(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};}
async function bounded(promise,label){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(label+' timed out')),15000);})]);}finally{clearTimeout(timer);}}

module.exports=async function checkNoteRecovery({page,check,baseUrl,token}){
 const auth={Authorization:'Bearer '+token},held=[],writes=[],unique=crypto.randomUUID(),originalViewport=page.viewportSize();let actualDownloadCount=0;
 const v1={known:'복구 v1 한글·日本語·😀\n"정확한 인용"',intention:'옛 의도 α',alternative:'조건부 대안 👀 <노트>',outcome:'사후 결과는 당시 근거와 분리'};
 const v2={known:'복구 v2 다른 근거 β',intention:'두 번째 의도',alternative:'두 번째 대안',outcome:'두 번째 사후 기록'};
 const v3={known:'현재 저장 v3',intention:'현재 의도 γ',alternative:'현재 대안',outcome:'현재 사후 메모'};
 const dirty={known:'복구 전에 작성한 미저장 초안 😀',intention:'초안 의도',alternative:'새 초안 대안',outcome:'초안 사후 기록'};
 const external={known:'다른 저장 경로에서 실제 v5',intention:'v5 의도',alternative:'v5 대안',outcome:'v5 사후 기록'};
 const track=request=>{if(request.method()==='PUT'&&new URL(request.url()).pathname.startsWith('/dev/v1/research/')){const body=request.postDataJSON();writes.push({route:new URL(request.url()).pathname,expected_revision:body.expected_revision,note:body.note});}};
 page.on('request',track);
 const trackDownload=()=>{actualDownloadCount++;};page.on('download',trackDownload);
 async function api(route,method='GET',data){const response=await page.context().request.fetch(baseUrl+'/dev/v1'+route,{method,headers:auth,...(data===undefined?{}:{data})});return {status:response.status(),body:await response.json()};}
 const noteRoute=(id,anchor='overview')=>'/research/'+id+'/notes/'+anchor;
 async function source(label,notes=[v1],video=false){const payload=video?{source_type:'transcript',title:'Recovery '+label+' '+unique,video_id:'CejHqSces8Q',raw_text:'YouTube transcript\nVideo ID: CejHqSces8Q\nLanguage: en\nCaptions: manual\n\n[0:01] wave '+unique+' '+label+'\n[0:02] roam '+unique+' '+label}:{source_type:'raw_json',title:'Recovery '+label+' '+unique,raw_text:JSON.stringify({synthetic_note:label+' '+unique})};const response=await api('/research','POST',payload);if(response.status!==201)throw Error('Real recovery source creation failed');for(const [index,note]of notes.entries()){const saved=await api(noteRoute(response.body.id),'PUT',{note,expected_revision:index});if(saved.status!==200||saved.body.revision!==index+1)throw Error('Real recovery note fixture save failed');}return response.body;}
 async function reconnect(){await page.reload();if(!(await page.evaluate(()=>Boolean(sessionStorage.getItem('lol-coach-dev-token'))))){await page.fill('#token',token);await page.click('#login-form button');}await page.waitForFunction(()=>!document.getElementById('workspace').hidden&&document.getElementById('notice').textContent.startsWith('연결됐습니다.'));await page.click('#show-research');}
 async function native(action,response='accept'){const pending=page.waitForEvent('dialog'),clicked=action(),dialog=await bounded(pending,'Native note recovery confirmation');const record={type:dialog.type(),message:dialog.message(),response};if(response==='accept')await dialog.accept();else await dialog.dismiss();await clicked;return record;}
 async function details(){const element=page.locator('details').filter({has:page.locator('#r-history-load')});if(!(await element.evaluate(node=>node.open)))await element.locator('summary').click();}
 async function open(resource,revision){await page.click('#show-research');const selector='#r-list button[data-resource-id="'+resource.id+'"]';await page.waitForSelector(selector);if(await page.evaluate(()=>rDirty))await native(()=>page.click(selector));else await page.click(selector);await page.waitForFunction(expected=>rResource&&rResource.id===expected.id&&rNote&&rNote.anchor==='overview'&&rNote.revision===expected.revision&&!document.getElementById('r-known').disabled,{id:resource.id,revision});await details();}
 async function load(count){await page.click('#r-history-load');await page.waitForFunction(number=>!document.getElementById('r-history-revision').disabled&&document.getElementById('r-history-revision').options.length===number+1,count);}
 async function preview(revision){await page.selectOption('#r-history-revision',String(revision));await page.waitForFunction(number=>rHistoryPreview&&rHistoryPreview.revision===number&&!document.getElementById('r-history-recover').disabled,revision);}
 async function fill(note){for(const field of fields)await page.fill('#r-'+field,note[field]);}
 async function editor(){return page.evaluate(names=>({note:rNote,resource_id:rResource&&rResource.id,edit:rEdit,epoch:rEpoch,dirty:rDirty,values:Object.fromEntries(names.map(field=>[field,document.getElementById('r-'+field).value])),note_state:document.getElementById('r-note-state').textContent,notice:document.getElementById('r-notice').textContent,save_disabled:document.getElementById('r-save').disabled,fields_disabled:document.getElementById('r-known').disabled,detail_hidden:document.getElementById('r-detail').hidden,authenticated:Boolean(sessionStorage.getItem('lol-coach-dev-token')),workspace_hidden:document.getElementById('workspace').hidden}),fields);}
 async function history(){return page.evaluate(()=>({preview:rHistoryPreview,owner:rHistoryOwner,text:document.getElementById('r-history-preview').textContent,hidden:document.getElementById('r-history-preview').hidden,recover_disabled:document.getElementById('r-history-recover').disabled,status:document.getElementById('r-history-state').textContent}));}
 async function holdRead(routePath,action){const pattern='**/dev/v1'+routePath,ready=deferred(),gate=deferred(),delivered=deferred();let active=true;const handler=async route=>{if(!active||route.request().method()!=='GET')return route.continue();active=false;try{const response=await route.fetch(),body=await response.json();ready.resolve({status:response.status(),body});await gate.promise;await route.fulfill({response});delivered.resolve();}catch(error){ready.reject(error);delivered.reject(error);await route.abort().catch(()=>{});}};await page.route(pattern,handler);held.push({pattern,handler,release:()=>gate.resolve()});await action();const actual=await bounded(ready.promise,'Genuine history GET before delayed delivery');return {actual,release:async()=>{gate.resolve();await bounded(delivered.promise,'Genuine history delivery');await page.evaluate(()=>new Promise(resolve=>setTimeout(resolve,0)));await page.unroute(pattern,handler);}};}
 async function holdDeleteDispatch(resource){const pattern='**/dev/v1/research/'+resource.id,requested=deferred(),gate=deferred(),delivered=deferred();let active=true;const handler=async route=>{if(!active||route.request().method()!=='DELETE')return route.continue();active=false;requested.resolve();try{await gate.promise;const response=await route.fetch(),body=await response.json();await route.fulfill({response});delivered.resolve({status:response.status(),body});}catch(error){delivered.reject(error);await route.abort().catch(()=>{});}};await page.route(pattern,handler);held.push({pattern,handler,release:()=>gate.resolve()});const confirmation=await native(()=>page.click('#r-delete'));await bounded(requested.promise,'Native DELETE before genuine backend dispatch');return {confirmation,commit:async()=>{gate.resolve();const actual=await bounded(delivered.promise,'Actual DELETE commit and delivery');await page.evaluate(()=>new Promise(resolve=>setTimeout(resolve,0)));await page.unroute(pattern,handler);return actual;}};}
 try{
  await reconnect();const a=await source('A',[v1,v2,v3]),b=await source('B');
  const rule={patch_range:'UNKNOWN',applicability:{champion:'UNKNOWN',role:'UNKNOWN',matchup:'UNKNOWN',level:'UNKNOWN',context:'UNKNOWN'},required_fields:['UNKNOWN'],claim:'복구 후에도 원본 출처 버전에 연결된 탐색 제안',mechanism:'UNKNOWN',counterexamples:['UNKNOWN'],author:'synthetic recovery test',limitations:['자동 코칭 미적용']};
  const proposed=await api('/knowledge/proposals','POST',{rule,source:{resource_id:a.id,anchor:'overview',note_revision:1},rule_id:null,expected_version:null});if(proposed.status!==201)throw Error('Actual source-bound Knowledge fixture failed');const knowledgePath='/knowledge/proposals/'+proposed.body.rule_id+'/versions/'+proposed.body.version,knowledgeBefore=await api(knowledgePath),oldVersionsBefore=await Promise.all([1,2,3].map(revision=>api(noteRoute(a.id)+'/revisions/'+revision)));
  await open(a,3);await fill(dirty);await load(3);await preview(1);const cancelBefore=await editor(),cancelHistoryBefore=await history(),cancelWrites=writes.length,cancel=await native(()=>page.click('#r-history-recover'),'dismiss');const cancelAfter=await editor(),cancelHistoryAfter=await history();
  check('note-recovery-native-cancel-keeps-current-dirty-note-no-put',cancel.type==='confirm'&&cancel.response==='dismiss'&&equal(cancelAfter,cancelBefore)&&equal(cancelHistoryAfter,cancelHistoryBefore)&&writes.length===cancelWrites&&cancelAfter.note.revision===3,{native_confirmation:cancel,exact_dirty_editor_retained:equal(cancelAfter,cancelBefore),exact_owned_preview_retained:equal(cancelHistoryAfter,cancelHistoryBefore),browser_put_delta:writes.length-cancelWrites,loaded_current_revision:cancelAfter.note.revision});
  const recoverBefore=await editor(),recoveryWrites=writes.length,accept=await native(()=>page.click('#r-history-recover'));const recovered=await editor(),actualOld=await api(noteRoute(a.id)+'/revisions/1');
  check('note-recovery-explicit-exact-unicode-draft-keeps-loaded-cas-no-put',accept.type==='confirm'&&actualOld.status===200&&equal(actualOld.body.note,v1)&&equal(recovered.values,v1)&&equal(recovered.note,recoverBefore.note)&&recovered.note.revision===3&&recovered.edit>recoverBefore.edit&&recovered.dirty&&!recovered.save_disabled&&writes.length===recoveryWrites&&(recovered.note_state.includes('미저장')||recovered.notice.includes('미저장')),{native_confirmation:accept,exact_four_unicode_fields:equal(recovered.values,v1),loaded_note_revision_unchanged:recovered.note.revision,current_saved_note_unchanged:equal(recovered.note,recoverBefore.note),browser_put_delta:writes.length-recoveryWrites,dirty:recovered.dirty,save_enabled:!recovered.save_disabled});
  const savePending=page.waitForResponse(response=>response.request().method()==='PUT'&&new URL(response.url()).pathname==='/dev/v1'+noteRoute(a.id));await page.click('#r-save');const saveResponse=await savePending,saveBody=await saveResponse.json(),saveRequest=saveResponse.request().postDataJSON();await page.waitForFunction(()=>rNote&&rNote.revision===4&&!rDirty&&!document.getElementById('r-save').disabled);const knowledgeAfter=await api(knowledgePath),oldVersionsAfter=await Promise.all([1,2,3].map(revision=>api(noteRoute(a.id)+'/revisions/'+revision))),latest4=await api(noteRoute(a.id));
  check('note-recovery-save-uses-current-plus-one-preserves-old-notes-and-knowledge-source',saveResponse.status()===200&&saveRequest.expected_revision===3&&equal(saveRequest.note,v1)&&saveBody.revision===4&&latest4.body.revision===4&&fields.every(field=>latest4.body[field]===v1[field])&&oldVersionsAfter.every((row,index)=>row.status===200&&equal(row.body.note,oldVersionsBefore[index].body.note)&&equal(row.body.note,[v1,v2,v3][index]))&&knowledgeBefore.status===200&&knowledgeAfter.status===200&&equal(knowledgeAfter.body,knowledgeBefore.body)&&knowledgeAfter.body.source_refs[0].note_revision===1&&knowledgeAfter.body.source_refs[0].note_sha256===hash(Buffer.from(canonical(v1)))&&knowledgeAfter.body.review_state==='EXPLORATORY'&&knowledgeAfter.body.coaching_enabled===false,{actual_put_status:saveResponse.status(),actual_expected_revision:saveRequest.expected_revision,new_saved_revision:saveBody.revision,all_old_payloads_immutable:oldVersionsAfter.every((row,index)=>equal(row.body.note,oldVersionsBefore[index].body.note)),saved_knowledge_exactly_unchanged:equal(knowledgeAfter.body,knowledgeBefore.body),knowledge_before_sha256:hash(Buffer.from(canonical(knowledgeBefore.body))),knowledge_after_sha256:hash(Buffer.from(canonical(knowledgeAfter.body))),source_note_revision:knowledgeAfter.body.source_refs[0].note_revision,source_note_sha256:knowledgeAfter.body.source_refs[0].note_sha256});
  await load(4);await preview(2);await page.click('#r-history-recover');const conflictBefore=await editor();const externalSave=await api(noteRoute(a.id),'PUT',{note:external,expected_revision:4});if(externalSave.status!==200||externalSave.body.revision!==5)throw Error('Actual external recovery conflict setup failed');const conflictPending=page.waitForResponse(response=>response.request().method()==='PUT'&&new URL(response.url()).pathname==='/dev/v1'+noteRoute(a.id));await page.click('#r-save');const conflictResponse=await conflictPending,conflictBody=await conflictResponse.json(),conflictRequest=conflictResponse.request().postDataJSON();await page.waitForFunction(()=>document.getElementById('r-notice').textContent.includes('REVISION_CONFLICT')&&!document.getElementById('r-save').disabled);const conflictAfter=await editor(),conflictHistory=await history(),latest5=await api(noteRoute(a.id));
  check('note-recovery-real-external-conflict-keeps-recovered-draft-current-cas',conflictResponse.status()===409&&conflictBody.error_code==='REVISION_CONFLICT'&&conflictRequest.expected_revision===4&&equal(conflictRequest.note,v2)&&equal(conflictAfter.values,conflictBefore.values)&&equal(conflictAfter.note,conflictBefore.note)&&conflictAfter.note.revision===4&&conflictAfter.dirty&&!conflictAfter.save_disabled&&conflictAfter.authenticated&&!conflictAfter.workspace_hidden&&!conflictHistory.recover_disabled&&latest5.body.revision===5&&fields.every(field=>latest5.body[field]===external[field]),{actual_http_status:conflictResponse.status(),actual_error_code:conflictBody.error_code,submitted_expected_revision:conflictRequest.expected_revision,exact_recovered_draft_retained:equal(conflictAfter.values,v2),loaded_cas_retained:conflictAfter.note.revision,backend_latest_revision:latest5.body.revision,recovery_reenabled:!conflictHistory.recover_disabled,authenticated:conflictAfter.authenticated});
  const navigationRead=await holdRead(noteRoute(a.id)+'/revisions/1',()=>page.selectOption('#r-history-revision','1'));await open(b,1);const navigationBefore=await editor(),navigationHistoryBefore=await history(),navigationWrites=writes.length;await navigationRead.release();await page.evaluate(()=>rHistoryRecover());const navigationAfter=await editor(),navigationHistoryAfter=await history();
  check('note-recovery-delayed-preview-cannot-recover-into-new-resource',navigationRead.actual.status===200&&navigationRead.actual.body.resource_id===a.id&&equal(navigationAfter,navigationBefore)&&equal(navigationHistoryAfter,navigationHistoryBefore)&&navigationAfter.resource_id===b.id&&navigationHistoryAfter.preview===null&&navigationHistoryAfter.recover_disabled&&writes.length===navigationWrites,{held_actual_status:navigationRead.actual.status,current_resource_is_b:navigationAfter.resource_id===b.id,exact_b_editor_retained:equal(navigationAfter,navigationBefore),stale_preview_not_recoverable:navigationHistoryAfter.preview===null&&navigationHistoryAfter.recover_disabled,browser_put_delta:writes.length-navigationWrites});
  await open(a,5);await load(5);const viewRead=await holdRead(noteRoute(a.id)+'/revisions/1',()=>page.selectOption('#r-history-revision','1'));await page.click('#show-synthetic');const viewBefore=await editor(),viewHistoryBefore=await history();await viewRead.release();await page.evaluate(()=>rHistoryRecover());const viewAfter=await editor(),viewHistoryAfter=await history();await page.click('#show-research');await load(5);const logoutRead=await holdRead(noteRoute(a.id)+'/revisions/1',()=>page.selectOption('#r-history-revision','1'));await page.click('#show-synthetic');await page.click('#logout');const logoutBefore=await editor(),logoutHistoryBefore=await history();await logoutRead.release();await page.evaluate(()=>rHistoryRecover());const logoutAfter=await editor(),logoutHistoryAfter=await history();
  check('note-recovery-delayed-preview-view-and-logout-owners-blocked',viewRead.actual.status===200&&equal(viewAfter,viewBefore)&&equal(viewHistoryAfter,viewHistoryBefore)&&viewHistoryAfter.recover_disabled&&viewHistoryAfter.preview===null&&logoutRead.actual.status===200&&equal(logoutAfter,logoutBefore)&&equal(logoutHistoryAfter,logoutHistoryBefore)&&!logoutAfter.authenticated&&logoutAfter.workspace_hidden&&logoutHistoryAfter.preview===null&&logoutHistoryAfter.recover_disabled,{held_view_status:viewRead.actual.status,view_editor_and_history_retained:equal(viewAfter,viewBefore)&&equal(viewHistoryAfter,viewHistoryBefore),held_logout_status:logoutRead.actual.status,logout_editor_and_history_retained:equal(logoutAfter,logoutBefore)&&equal(logoutHistoryAfter,logoutHistoryBefore),logged_out:!logoutAfter.authenticated,stale_recovery_disabled:logoutHistoryAfter.recover_disabled});
  // DELETE clears the editor before awaiting its genuine list refresh. Bind
  // the before snapshot to the existing completed-delete notice, so the
  // handler's own notice update is not mistaken for late-preview mutation.
  await reconnect();const deleting=await source('delete-held-preview');await open(deleting,1);await load(1);const deleteRead=await holdRead(noteRoute(deleting.id)+'/revisions/1',()=>page.selectOption('#r-history-revision','1'));const deletePending=page.waitForResponse(response=>response.request().method()==='DELETE'&&new URL(response.url()).pathname==='/dev/v1/research/'+deleting.id),deleteConfirm=await native(()=>page.click('#r-delete'));const deleteResponse=await deletePending;await page.waitForFunction(()=>rResource===null&&rNote===null&&document.getElementById('r-notice').textContent==='자료와 노트를 삭제했습니다.');const deleteBefore=await editor(),deleteHistoryBefore=await history();await deleteRead.release();await page.evaluate(()=>rHistoryRecover());const deleteAfter=await editor(),deleteHistoryAfter=await history(),missingSource=await api('/research/'+deleting.id),missingHistory=await api(noteRoute(deleting.id)+'/history');
  check('note-recovery-current-delete-cannot-recover-delayed-removed-preview',deleteRead.actual.status===200&&deleteResponse.status()===200&&deleteConfirm.type==='confirm'&&equal(deleteAfter,deleteBefore)&&equal(deleteHistoryAfter,deleteHistoryBefore)&&deleteAfter.note===null&&fields.every(field=>deleteAfter.values[field]==='')&&deleteHistoryAfter.preview===null&&deleteHistoryAfter.recover_disabled&&missingSource.status===404&&missingHistory.status===404&&(await api(knowledgePath)).status===200,{held_actual_preview_status:deleteRead.actual.status,actual_delete_status:deleteResponse.status(),native_confirmation:deleteConfirm,exact_cleared_state_retained:equal(deleteAfter,deleteBefore)&&equal(deleteHistoryAfter,deleteHistoryBefore),deleted_source_status:missingSource.status,deleted_history_status:missingHistory.status,original_knowledge_survives:true});
  const same=await source('same-source-anchors',[v1],true);const cueSave=await api(noteRoute(same.id,'1'),'PUT',{note:v2,expected_revision:0});if(cueSave.status!==200)throw Error('Actual recovery anchor fixture failed');await open(same,1);const sameDelete=await holdDeleteDispatch(same);await page.click('#r-candidates button[data-anchor="1"]');await page.waitForFunction(()=>rNote&&rNote.anchor==='1'&&!document.getElementById('r-known').disabled);await load(1);await preview(1);await page.fill('#r-known','새 구간에서 직접 쓰던 미저장 초안');const sameBefore=await editor(),samePreviewBefore=await history(),sameCommitted=await sameDelete.commit();await page.waitForFunction(()=>rResource===null&&rNote===null&&rHistoryPreview===null&&document.getElementById('r-history-recover').disabled);const sameHistoryAfter=await history(),sameDownloadsBefore=actualDownloadCount;await page.evaluate(()=>{rHistoryRecover();document.getElementById('r-download').click();});await page.evaluate(()=>new Promise(resolve=>setTimeout(resolve,0)));const sameAfter=await editor(),sameBlockedDownloadDelta=actualDownloadCount-sameDownloadsBefore;
  const unrelated=await source('unrelated-stale-delete');await open(unrelated,1);const unrelatedDelete=await holdDeleteDispatch(unrelated);await open(b,1);await load(1);await preview(1);await page.fill('#r-known','B 독립 미저장 초안 유지');const independentBefore=await editor(),independentHistoryBefore=await history(),unrelatedCommitted=await unrelatedDelete.commit(),independentAfter=await editor(),independentHistoryAfter=await history();
  const pendingDeleted=await source('inactive-source-while-b-loading');await open(pendingDeleted,1);const pendingDelete=await holdDeleteDispatch(pendingDeleted),pendingBRead=await holdRead('/research/'+b.id,()=>page.click('#r-list button[data-resource-id="'+b.id+'"]')),pendingBBeforeDelete=await editor(),pendingCommitted=await pendingDelete.commit();await page.waitForFunction(()=>rResource===null&&rNote===null);const pendingBAfterDelete=await editor();await pendingBRead.release();await page.waitForFunction(id=>rResource&&rResource.id===id&&rNote&&rNote.revision===1&&!document.getElementById('r-known').disabled,b.id);const pendingBLoaded=await editor();
  check('note-recovery-stale-delete-source-event-matches-current-resource-only',sameBefore.resource_id===same.id&&sameBefore.note.anchor==='1'&&samePreviewBefore.preview.anchor==='1'&&!samePreviewBefore.recover_disabled&&sameCommitted.status===200&&sameAfter.resource_id===null&&sameAfter.note===null&&fields.every(field=>sameAfter.values[field]==='')&&sameAfter.detail_hidden&&sameBlockedDownloadDelta===0&&sameHistoryAfter.preview===null&&sameHistoryAfter.owner===null&&sameHistoryAfter.recover_disabled&&(await api('/research/'+same.id)).status===404&&unrelatedCommitted.status===200&&equal(independentAfter,independentBefore)&&equal(independentHistoryAfter,independentHistoryBefore)&&independentAfter.resource_id===b.id&&independentAfter.dirty&&!independentHistoryAfter.recover_disabled&&pendingBRead.actual.status===200&&pendingCommitted.status===200&&pendingBAfterDelete.resource_id===null&&pendingBAfterDelete.note===null&&fields.every(field=>pendingBAfterDelete.values[field]==='')&&pendingBAfterDelete.epoch===pendingBBeforeDelete.epoch&&pendingBLoaded.resource_id===b.id&&pendingBLoaded.note.resource_id===b.id&&pendingBLoaded.note.revision===1&&!pendingBLoaded.fields_disabled&&(await api('/research/'+b.id)).status===200,{genuine_delete_dispatch_gates:true,same_resource_actual_delete_status:sameCommitted.status,same_resource_anchor:'1',deleted_cached_resource_note_and_editor_purged:sameAfter.resource_id===null&&sameAfter.note===null&&fields.every(field=>sameAfter.values[field]===''),deleted_note_download_events:sameBlockedDownloadDelta,same_resource_recovery_owner_cleared:sameHistoryAfter.preview===null&&sameHistoryAfter.owner===null,unrelated_actual_delete_status:unrelatedCommitted.status,independent_b_draft_and_preview_retained:equal(independentAfter,independentBefore)&&equal(independentHistoryAfter,independentHistoryBefore),held_real_b_get_status:pendingBRead.actual.status,pending_delete_actual_status:pendingCommitted.status,inactive_deleted_cache_purged:pendingBAfterDelete.resource_id===null&&pendingBAfterDelete.note===null,pending_b_generation_not_cancelled:pendingBAfterDelete.epoch===pendingBBeforeDelete.epoch,real_b_navigation_completed:pendingBLoaded.resource_id===b.id&&pendingBLoaded.note.revision===1&&!pendingBLoaded.fields_disabled});
  const rawLineNote={known:'원본 CRLF\r\n두 줄\r끝',intention:'의도\r계속',alternative:'대안\r\n다음',outcome:'사후\r결과'},nativeLineNote={known:'원본 CRLF\n두 줄\n끝',intention:'의도\n계속',alternative:'대안\n다음',outcome:'사후\n결과'};
  const lineSource=await source('original-line-endings',[rawLineNote,v3]),lineProposal=await api('/knowledge/proposals','POST',{rule,source:{resource_id:lineSource.id,anchor:'overview',note_revision:1},rule_id:null,expected_version:null});if(lineProposal.status!==201)throw Error('Actual raw-line source proposal setup failed');const lineKnowledgePath='/knowledge/proposals/'+lineProposal.body.rule_id+'/versions/'+lineProposal.body.version,lineKnowledgeBefore=await api(lineKnowledgePath);
  await open(lineSource,2);await load(2);await preview(1);const originalRawPreview=await api(noteRoute(lineSource.id)+'/revisions/1'),lineCurrentBefore=await editor(),lineDownloadPending=page.waitForEvent('download');await page.click('#r-history-download');const lineDownload=await bounded(lineDownloadPending,'Actual original-CRLF history download'),lineStream=await lineDownload.createReadStream();if(!lineStream)throw Error('Actual raw-line download stream unavailable');const lineChunks=[];for await(const chunk of lineStream)lineChunks.push(chunk);const lineDownloadBytes=Buffer.concat(lineChunks),lineDownloadText=lineDownloadBytes.toString('utf8');
  await page.click('#r-history-recover');const lineRecovered=await editor(),lineSavePending=page.waitForResponse(response=>response.request().method()==='PUT'&&new URL(response.url()).pathname==='/dev/v1'+noteRoute(lineSource.id));await page.click('#r-save');const lineSaveResponse=await lineSavePending,lineSaveBody=await lineSaveResponse.json(),lineSaveRequest=lineSaveResponse.request().postDataJSON();await page.waitForFunction(()=>rNote&&rNote.revision===3&&!rDirty&&!document.getElementById('r-save').disabled);const originalRawAfter=await api(noteRoute(lineSource.id)+'/revisions/1'),lineKnowledgeAfter=await api(lineKnowledgePath);
  check('note-recovery-native-line-endings-preserve-original-history-download-and-source-hash',originalRawPreview.status===200&&equal(originalRawPreview.body.note,rawLineNote)&&lineDownloadText===JSON.stringify(originalRawPreview.body,null,2)&&equal(JSON.parse(lineDownloadText).note,rawLineNote)&&lineDownload.suggestedFilename()==='lol-coach-note-v1.json'&&equal(lineRecovered.values,nativeLineNote)&&equal(lineRecovered.note,lineCurrentBefore.note)&&lineRecovered.note.revision===2&&lineRecovered.dirty&&lineSaveResponse.status()===200&&lineSaveRequest.expected_revision===2&&equal(lineSaveRequest.note,nativeLineNote)&&lineSaveBody.revision===3&&fields.every(field=>lineSaveBody[field]===nativeLineNote[field])&&originalRawAfter.status===200&&equal(originalRawAfter.body.note,rawLineNote)&&equal(lineKnowledgeAfter.body,lineKnowledgeBefore.body)&&lineKnowledgeAfter.body.source_refs[0].note_revision===1&&lineKnowledgeAfter.body.source_refs[0].note_sha256===hash(Buffer.from(canonical(rawLineNote))),{original_crlf_cr_note_preserved:equal(originalRawAfter.body.note,rawLineNote),native_editor_literal_lf:equal(lineRecovered.values,nativeLineNote),original_download_exact_bytes:lineDownloadText===JSON.stringify(originalRawPreview.body,null,2),original_download_utf8_sha256:hash(lineDownloadBytes),actual_saved_lf_note:equal(lineSaveRequest.note,nativeLineNote),actual_expected_revision:lineSaveRequest.expected_revision,new_revision:lineSaveBody.revision,knowledge_exactly_unchanged:equal(lineKnowledgeAfter.body,lineKnowledgeBefore.body),original_source_note_sha256:lineKnowledgeAfter.body.source_refs[0].note_sha256});
  await open(a,5);await load(5);await preview(1);await page.setViewportSize({width:390,height:844});await page.locator('#r-history-recover').scrollIntoViewIfNeeded();const responsive=await page.locator('#r-history-recover').evaluate(element=>{const box=element.getBoundingClientRect();return {disabled:element.disabled,width:box.width,left:box.left,right:box.right,viewport:window.innerWidth,document_width:document.documentElement.scrollWidth,visible:Boolean(element.getClientRects().length)};});const mobileEditor=await editor();
  check('note-recovery-mobile-390-control-visible-without-horizontal-overflow',responsive.visible&&!responsive.disabled&&responsive.width>0&&responsive.left>=0&&responsive.right<=responsive.viewport+1&&responsive.viewport===390&&responsive.document_width<=391&&mobileEditor.note.revision===5&&!mobileEditor.dirty,{viewport_width:responsive.viewport,document_width:responsive.document_width,control_visible:responsive.visible,control_enabled:!responsive.disabled,control_bounds:{left:responsive.left,right:responsive.right,width:responsive.width},current_saved_revision:mobileEditor.note.revision});
 }finally{for(const route of held)route.release();for(const route of held)await page.unroute(route.pattern,route.handler);page.off('request',track);page.off('download',trackDownload);if(originalViewport)await page.setViewportSize(originalViewport);}
};
