'use strict';
// Actual production draft.js in a synthetic DOM/deferred-service harness.
// These receipts never establish actual HTTP/browser/SQLite or game evidence.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),sourcePath=path.resolve(process.argv[3]||path.join(root,'web_r4/draft.js'));
const source=fs.existsSync(sourcePath)?fs.readFileSync(sourcePath,'utf8'):null;
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const clone=value=>JSON.parse(JSON.stringify(value));
function canonical(value){if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}';return JSON.stringify(value);}
const same=(a,b)=>canonical(a)===canonical(b);
function deferred(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};}
const A='a'.repeat(32),B='b'.repeat(32);
const input=title=>({title,phase:null,patch:null,observed_at:null,visible_picks:[{side:'ALLY',slot:1,champion:'Ashe'}],visible_bans:[],role_assignments:[],source:{author:'manual author',perspective:'UNKNOWN',description:'synthetic operator declaration, not verified player POV'}});
const captures={A1:input('SAVED-A-PRIVATE-1 α'),A2:input('SAVED-A-PRIVATE-2 β'),A3:input('SAVED-A-PRIVATE-3 한글 😀'),B1:input('SAVED-B-PRIVATE-1 β')};
const snapshotId=(cid,revision)=>hash('synthetic-snapshot:'+cid+':'+revision).slice(0,32);
function record(cid,revision,capture){return {schema_version:'mvp.manual-draft.v1',id:snapshotId(cid,revision),session_id:cid,revision,parent_id:revision===1?null:snapshotId(cid,revision-1),received_at:'2026-10-05T00:00:00+00:00',capture:clone(capture),input_sha256:hash(canonical(capture)),adapter_capability:{automatic_collection:'UNAVAILABLE',manual_capture:'AVAILABLE'},validation_state:'UNVERIFIED',gameplan_status:'NOT_GENERATED',coaching_enabled:false};}
const fixtures={A1:record(A,1,captures.A1),A2:record(A,2,captures.A2),A3:record(A,3,captures.A3),B1:record(B,1,captures.B1)};
const textIds=['title','phase','patch','observed','author','perspective','source'];
const slotIds=[];for(const side of ['ALLY','ENEMY'])for(let slot=1;slot<=5;slot++)for(const field of ['pick','ban','role','uncertainty'])slotIds.push(field+'-'+side+'-'+slot);
const inputIds=[...textIds,...slotIds];
function serviceError(status,message){const error=new Error(message);error.status=status;return error;}
function harness({latest=1,heldHistory=false,heldOpenA=false,heldOpenB=false}={}){
 if(source===null)throw Error('MISSING_MANUAL_DRAFT_UI: web_r4/draft.js is absent');
 const elements=new Map(),calls=[],exports=[],confirmations=[],saveQueue=[],historyReply=deferred(),openAReply=deferred(),openBReply=deferred(),deleteReply=deferred(),stored=new Map([[1,clone(fixtures.A1)],[2,clone(fixtures.A2)],[3,clone(fixtures.A3)]].filter(([revision])=>revision<=latest));let deleted=false,authClears=0;
 function el(id){if(!elements.has(id))elements.set(id,{value:'',disabled:false,hidden:false,textContent:'',dataset:{},listeners:{},children:[],options:[],addEventListener(type,fn){this.listeners[type]=fn;},replaceChildren(...children){this.children=[...children];this.options=[...children];},append(child){this.children.push(child);this.options.push(child);},click(){if(this.listeners.click)return this.listeners.click();}});return elements.get(id);}
 const blobs=new Map();let blobNumber=0;
 class TestBlob{constructor(parts){this.bytes=parts.join('');}}
 function node(tag,text=''){const element={textContent:text,value:'',dataset:{},addEventListener(){},append(){},click(){if(tag==='a')exports.push(blobs.get(this.href));}};return element;}
 let keyNumber=0;
 const api=async(route,method='GET',body,idem)=>{
  calls.push({route,method,...(body===undefined?{}:{body:clone(body)}),idempotency_key:idem||null});
  if(method==='PUT'){const queued=deferred();saveQueue.push({body:clone(body),idem,queued});return queued.promise;}
  if(method==='DELETE')return deleteReply.promise;
  if(route==='/draft-captures')return [...(deleted?[]:[clone(stored.get(latest))]),clone(fixtures.B1)];
  if(route==='/draft-captures/'+A+'/history'){if(deleted)throw serviceError(404,'DRAFT_CAPTURE_NOT_FOUND');return {session_id:A,current_revision:latest,revision_count:latest,revisions:Array.from({length:latest},(_,i)=>i+1)};}
  if(route==='/draft-captures/'+B+'/history')return {session_id:B,current_revision:1,revision_count:1,revisions:[1]};
  if(route==='/draft-captures/'+B)return heldOpenB?openBReply.promise:clone(fixtures.B1);
  if(route==='/draft-captures/'+A){if(deleted)throw serviceError(404,'DRAFT_CAPTURE_NOT_FOUND');return clone(stored.get(latest));}
  const old='/draft-captures/'+A+'/revisions/1';
  if(route===old){if(deleted)throw serviceError(404,'DRAFT_CAPTURE_NOT_FOUND');if(heldHistory)return historyReply.promise;if(heldOpenA)return openAReply.promise;return clone(fixtures.A1);}
  const matched=route.match(new RegExp('^/draft-captures/'+A+'/revisions/(\\d+)$'));
  if(matched){if(deleted||!stored.has(Number(matched[1])))throw serviceError(404,'DRAFT_CAPTURE_NOT_FOUND');return clone(stored.get(Number(matched[1])));}
  throw Error('Unexpected synthetic service route '+method+' '+route);
 };
 const context=vm.createContext({$:el,node,document:{addEventListener(){},querySelector:()=>el('query'),querySelectorAll:()=>[]},confirm:message=>{confirmations.push(message);return true;},error(){authClears++;},api,crypto:{randomUUID:()=>`draft-retry-key-${++keyNumber}`},Blob:TestBlob,URL:{createObjectURL(blob){const url='synthetic-blob-'+(++blobNumber);blobs.set(url,blob.bytes);return url;},revokeObjectURL(){}},setTimeout:fn=>{fn();return 0;},console});
 vm.runInContext(source,context,{filename:'web_r4/draft.js'});
 const evaluate=code=>vm.runInContext(code,context);
 const state=()=>JSON.parse(evaluate('JSON.stringify({record:dRecord,latest:dLatest,dirty:dDirty,edit:dEdit,epoch:dEpoch,preview:dPreview,notice:$("d-notice").textContent,values:Object.fromEntries('+JSON.stringify(inputIds)+'.map(id=>[id,$("d-"+id).value])),save_disabled:$("d-save").disabled,download_disabled:$("d-download").disabled,history_download_disabled:$("d-history-download").disabled})'));
 const edit=(id,value)=>{el('d-'+id).value=value;const listener=el('d-'+id).listeners.input||el('d-'+id).listeners.change;if(!listener)throw Error('Missing production edit listener for d-'+id);listener();};
 const save=()=>evaluate('dSave()'),open=(cid=A,revision)=>evaluate('dOpen('+JSON.stringify(cid)+(revision===undefined?'':','+revision)+')');
 const preview=()=>{el('d-history-revision').value='1';return evaluate('dHistoryOpen()');};
 const acceptSave=index=>{const entry=saveQueue[index];if(!entry)throw Error('Missing queued save '+index);const revision=entry.body.expected_revision+1,saved=record(A,revision,entry.body.capture);stored.set(revision,clone(saved));latest=revision;entry.queued.resolve(clone(saved));return saved;};
 const deleteCommit=()=>{deleted=true;deleteReply.resolve({id:A,status:'DELETED',deleted_snapshots:stored.size});};
 return {el,evaluate,state,calls,exports,confirmations,saveQueue,historyReply,openAReply,openBReply,edit,save,open,preview,acceptSave,deleteCommit,authClears:()=>authClears,remove:()=>evaluate('dDelete()')};
}
async function ready(options){const h=harness(options);await h.open();return h;}
async function tick(){await new Promise(resolve=>setTimeout(resolve,0));}
async function run(){const results=[];async function check(id,task){try{const actual=await task();results.push({id,passed:Object.values(actual.checks).every(Boolean),...actual});}catch(error){results.push({id,passed:false,error:error.message});}}
 await check('DRAFT-UI-LATE-ACK-KEEPS-LATER-DRAFT-AND-NEXT-CAS',async()=>{const h=await ready();h.edit('title','submitted draft α');const pending=h.save();h.edit('title','later draft 한글 😀');h.edit('pick-ALLY-1','새로운 선택 😀');const before=h.state(),saved2=h.acceptSave(0);await pending;const after=h.state();const next=h.save(),nextRequest=clone(h.saveQueue[1].body);h.acceptSave(1);await next;return {checks:{actual_ack_revision_applied:after.latest===2&&after.record.revision===2,later_editor_retained:same(after.values,before.values)&&after.dirty,saved_record_is_submitted_capture:same(after.record,saved2),next_cas_two:nextRequest.expected_revision===2,next_capture_is_later_draft:nextRequest.capture.title==='later draft 한글 😀'&&nextRequest.capture.visible_picks[0].champion==='새로운 선택 😀',unknown_time_patch_phase_not_fabricated:nextRequest.capture.observed_at===null&&nextRequest.capture.phase===null&&nextRequest.capture.patch===null},before,after,nextRequest,calls:h.calls};});
 await check('DRAFT-UI-OLD-409-401-CANNOT-CHANGE-NEW-B-DRAFT-OR-AUTH',async()=>{const scenarios=[];for(const status of [409,401]){const h=await ready();h.edit('title','old submitted A');const saving=h.save();await h.open(B);h.edit('title','B independent dirty draft 👀');const before=h.state();h.saveQueue[0].queued.reject(serviceError(status,status===409?'REVISION_CONFLICT':'synthetic unauthorized old request'));await saving;const after=h.state();scenarios.push({status,before,after,unchanged:same(after,before),auth_clears:h.authClears()});}return {checks:{every_new_b_state_unchanged:scenarios.every(item=>item.unchanged&&item.after.record.session_id===B&&item.after.dirty),no_stale_auth_reset:scenarios.every(item=>item.auth_clears===0)},scenarios};});
 await check('DRAFT-UI-CURRENT-CONFLICT-RETAINS-DRAFT-CURRENT-401-CLEARS',async()=>{const h=await ready();h.edit('title','current exact dirty draft 😀');const before=h.state(),saving=h.save();h.saveQueue[0].queued.reject(serviceError(409,'REVISION_CONFLICT'));await saving;const afterConflict=h.state(),unauthorized=h.save();h.saveQueue[1].queued.reject(serviceError(401,'synthetic current unauthorized request'));await unauthorized;const after401=h.state();return {checks:{current_conflict_visible:afterConflict.notice.includes('REVISION_CONFLICT'),exact_current_draft_and_cas_retained:same(afterConflict.values,before.values)&&same(afterConflict.record,before.record)&&afterConflict.latest===before.latest&&afterConflict.dirty,save_retry_enabled:!afterConflict.save_disabled,current_401_auth_cleared:h.authClears()===1,private_record_and_export_cleared:after401.record===null&&after401.preview===null&&after401.download_disabled&&!Object.values(after401.values).some(value=>typeof value==='string'&&value.includes('PRIVATE'))&&after401.values.title!==before.values.title},before,afterConflict,after401,auth_clears:h.authClears()};});
 await check('DRAFT-UI-HISTORY-READONLY-KEEPS-CURRENT-CAS-AND-SAVED-EXPORT',async()=>{const h=await ready({latest:3});h.edit('title','unsaved current edit 😀');const before=h.state();await h.preview();const after=h.state();h.el('d-download').listeners.click();h.el('d-history-download').listeners.click();const saved=JSON.parse(h.exports[0]),historical=JSON.parse(h.exports[1]);return {checks:{current_editor_and_cas_untouched:same(after.values,before.values)&&same(after.record,before.record)&&after.latest===3&&after.dirty&&after.edit===before.edit,exact_old_preview:same(after.preview,fixtures.A1),current_saved_export_not_draft:same(saved,fixtures.A3)&&saved.capture.title!==after.values.title,exact_historical_export:same(historical,fixtures.A1),no_put_from_history:h.calls.every(call=>call.method==='GET')},before,after,exported_saved_revision:saved.revision,exported_historical_revision:historical.revision,calls:h.calls};});
 await check('DRAFT-UI-LATE-HISTORY-CANNOT-FOLLOW-NAVIGATION-NEW-LOGOUT',async()=>{const scenarios=[];for(const action of ['navigation','new','logout']){const h=await ready({latest:3,heldHistory:true}),reading=h.preview();if(action==='navigation'){await h.open(B);h.edit('title','B exact dirty draft');}if(action==='new')await h.evaluate('dNew()');if(action==='logout')h.el('logout').listeners.click();const before=h.state();h.historyReply.resolve(clone(fixtures.A1));await reading;const after=h.state();scenarios.push({action,before,after,unchanged:same(after,before)});}return {checks:{each_current_context_unchanged:scenarios.every(item=>item.unchanged),no_stale_preview_export:scenarios.every(item=>item.after.preview===null&&item.after.history_download_disabled)},scenarios};});
 await check('DRAFT-UI-DELETE-INVALIDATES-SAME-CAPTURE-CACHED-OPEN-EXPORT',async()=>{const h=await ready({latest:3,heldOpenA:true}),removing=h.remove(),opening=h.open(A,1);await tick();h.deleteCommit();await removing;const beforeRelease=h.state();h.openAReply.resolve(clone(fixtures.A1));await opening;const after=h.state();return {checks:{delete_uses_actual_latest_revision:h.calls.some(call=>call.method==='DELETE'&&call.body.expected_revision===3),deleted_record_and_preview_purged:after.record===null&&after.preview===null,deleted_export_blocked:after.download_disabled&&after.history_download_disabled,deleted_private_form_purged:!Object.values(after.values).some(value=>typeof value==='string'&&value.includes('SAVED-A-PRIVATE')),late_open_cannot_resurrect:beforeRelease.record===null&&after.record===null},beforeRelease,after,calls:h.calls};});
 await check('DRAFT-UI-INACTIVE-A-DELETE-PURGES-CACHE-PRESERVES-PENDING-B',async()=>{const h=await ready({heldOpenB:true}),removing=h.remove(),opening=h.open(B);await tick();const pendingBefore=h.state();h.deleteCommit();await removing;const afterDelete=h.state();h.openBReply.resolve(clone(fixtures.B1));await opening;const afterB=h.state();return {checks:{inactive_deleted_export_purged:afterDelete.record===null&&afterDelete.download_disabled,pending_b_epoch_preserved:afterDelete.epoch===pendingBefore.epoch,inactive_a_private_form_purged:!Object.values(afterDelete.values).some(value=>typeof value==='string'&&value.includes('SAVED-A-PRIVATE')),pending_b_completed:afterB.record&&afterB.record.session_id===B&&afterB.latest===1&&!afterB.save_disabled,exact_b_source_unchanged:afterB.record&&same(afterB.record.capture,fixtures.B1.capture)},pendingBefore,afterDelete,afterB,calls:h.calls};});
 return {scope:'Manual draft UI concurrent edit/auth/history/deletion ownership only',verifier:'Node VM production script with synthetic DOM/service replies; not actual browser/HTTP/SQLite/game evidence',fixture_correction:'Distinct snapshot IDs per capture/revision; complete A1→A2→A3 chain; each service starts with only revisions through its declared latest. Earlier actual test bytes and RED receipts remain archived.',executed_at:new Date().toISOString(),node_version:process.version,source_exists:source!==null,source_sha256:source===null?null:hash(source),test_sha256:hash(fs.readFileSync(__filename)),fixture_sha256:hash(canonical(fixtures)),passed:results.filter(result=>result.passed).length,total:7,results};
}
run().then(receipt=>{const out=path.resolve(process.argv[2]||path.join(root,'evidence/mvp/draft-ui-after.json'));fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(receipt,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:receipt.passed,total:receipt.total,source_exists:receipt.source_exists,source_sha256:receipt.source_sha256,results:receipt.results.map(({id,passed})=>({id,passed}))}));process.exitCode=receipt.passed===receipt.total?0:1;}).catch(error=>{console.error(error);process.exitCode=1;});
