'use strict';
// Actual browser/server/SQLite proposal workflow. Genuine route.fetch delivery
// is held. The same-rule DELETE case also gates its native request dispatch so
// genuine C reads precede the actual DELETE commit. No API reply is fabricated.
const crypto=require('node:crypto');
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const ids=['patch','champion','role','matchup','level','context','required','claim','mechanism','counterexamples','author','limitations'];
function canonical(value){if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}';return JSON.stringify(value);}
const equal=(a,b)=>canonical(a)===canonical(b);
function deferred(){let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};}
async function bounded(promise,label){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error(label+' timed out')),15000);})]);}finally{clearTimeout(timer);}}

module.exports=async function checkKnowledge({page,check,baseUrl,token}){
 const auth={Authorization:'Bearer '+token},held=[],writes=[];
 const unique=crypto.randomUUID();
 const note={known:'PRIVATE-SAVED-NOTE-'+unique+' 한글 😀\n당시 근거',intention:'직접 쓴 의도',alternative:'대안 UNKNOWN',outcome:'사후 결과는 분리'};
 const initialRule={patch_range:'UNKNOWN',applicability:{champion:'UNKNOWN',role:'UNKNOWN',matchup:'UNKNOWN',level:'UNKNOWN',context:'상황 미검증 α\n조건 😀'},required_fields:['UNKNOWN','실제 관찰 필요'],claim:'탐색 주장 한글·日本語·😀\n"인용" <조건>',mechanism:'미검증 작동 가설 β',counterexamples:['UNKNOWN','반례는 아직 수집 전'],author:'개인 작성 테스트',limitations:['PLAYER 검증 아님','코칭에 미적용']};
 const track=request=>{if(request.method()==='POST'&&new URL(request.url()).pathname==='/dev/v1/knowledge/proposals')writes.push(request.postDataJSON());};
 page.on('request',track);
 async function api(route,method='GET',data){const response=await page.context().request.fetch(baseUrl+'/dev/v1'+route,{method,headers:auth,...(data===undefined?{}:{data})});return {status:response.status(),body:await response.json()};}
 const exact=record=>'/knowledge/proposals/'+record.rule_id+'/versions/'+record.version;
 const sourceRef=resource=>({resource_id:resource.id,anchor:'overview',note_revision:1});
 async function source(label,saved=true){const response=await api('/research','POST',{source_type:'raw_json',title:'Knowledge '+label+' '+unique,raw_text:JSON.stringify({synthetic_note:label+' '+unique})});if(response.status!==201)throw Error('Real Research source creation failed');if(saved){const put=await api('/research/'+response.body.id+'/notes/overview','PUT',{note,expected_revision:0});if(put.status!==200||put.body.revision!==1)throw Error('Real saved source note failed');}return response.body;}
 async function propose(resource,rule=initialRule,previous=null){const response=await api('/knowledge/proposals','POST',{rule,source:sourceRef(resource),rule_id:previous?previous.rule_id:null,expected_version:previous?previous.version:null});if(response.status!==201)throw Error('Real Knowledge fixture save failed '+response.status);return response.body;}
 async function chain(label){const s1=await source(label+'-1'),s2=await source(label+'-2'),s3=await source(label+'-3');const a=await propose(s1,{...initialRule,claim:label+' preserved A'}),b=await propose(s2,{...initialRule,claim:label+' deleted middle B'},a),c=await propose(s3,{...initialRule,claim:label+' DELETED-C-PRIVATE-SENTINEL'},b);return {s1,s2,s3,a,b,c};}
 async function native(action,response='accept'){const pending=page.waitForEvent('dialog'),clicked=action(),dialog=await bounded(pending,'Native Knowledge confirmation');const actual={type:dialog.type(),message:dialog.message(),response};if(response==='accept')await dialog.accept();else await dialog.dismiss();await clicked;return actual;}
 async function showResearch(){await page.click('#show-research');await page.waitForFunction(()=>!document.getElementById('research-view').hidden);}
 async function showKnowledge(){await page.click('#show-knowledge');await page.waitForFunction(()=>!document.getElementById('knowledge-view').hidden);}
 async function openResource(resource,revision=1){await showResearch();const selector='#r-list button[data-resource-id="'+resource.id+'"]';await page.waitForSelector(selector);if(await page.evaluate(()=>rDirty))await native(()=>page.click(selector));else await page.click(selector);await page.waitForFunction(expected=>rResource&&rResource.id===expected.id&&rNote&&rNote.revision===expected.revision&&!document.getElementById('r-known').disabled,{id:resource.id,revision});}
 async function newProposal(){await showKnowledge();if(await page.evaluate(()=>kDirty))await native(()=>page.click('#k-new'));else await page.click('#k-new');await page.waitForFunction(()=>kRecord===null&&kSource===null&&document.getElementById('k-claim').value==='');}
 async function openProposal(record){await showKnowledge();const selector='#k-list button[data-rule-id="'+record.rule_id+'"][data-version-id="'+record.version+'"]';await page.waitForSelector(selector);if(await page.evaluate(()=>kDirty))await native(()=>page.click(selector));else await page.click(selector);await page.waitForFunction(version=>kRecord&&kRecord.version===version&&!document.getElementById('k-claim').disabled,record.version);}
 async function useSource(resource){await openResource(resource);await showKnowledge();const confirm=await page.evaluate(()=>Boolean(kSource&&kDirty&&(kSource.resource_id!==rResource.id||kSource.anchor!==rNote.anchor||kSource.note_revision!==rNote.revision)));const actual=confirm?await native(()=>page.click('#k-use-note')):(await page.click('#k-use-note'),null);await page.waitForFunction(id=>kSource&&kSource.resource_id===id&&kSource.note_revision===1,resource.id);return actual;}
 async function fillRule(rule){const values={patch:rule.patch_range,...rule.applicability,claim:rule.claim,mechanism:rule.mechanism,author:rule.author,required:rule.required_fields.join('\n'),counterexamples:rule.counterexamples.join('\n'),limitations:rule.limitations.join('\n')};for(const id of ids)await page.fill('#k-'+id,values[id]);}
 async function state(){return page.evaluate(fieldIds=>({record:kRecord,latest:kLatest,source:kSource,dirty:kDirty,edit:kEdit,epoch:kEpoch,values:Object.fromEntries(fieldIds.map(id=>[id,document.getElementById('k-'+id).value])),notice:document.getElementById('k-notice').textContent,current:document.getElementById('k-current').textContent,source_text:document.getElementById('k-source').textContent,save_disabled:document.getElementById('k-save').disabled,download_disabled:document.getElementById('k-download').disabled,authenticated:Boolean(sessionStorage.getItem('lol-coach-dev-token')),workspace_hidden:document.getElementById('workspace').hidden,main_notice:document.getElementById('notice').textContent}),ids);}
 async function hold(method,predicate,action){const pattern='**/dev/v1/**',fetched=deferred(),gate=deferred(),delivered=deferred();let active=true;
  const handler=async route=>{const request=route.request(),path=new URL(request.url()).pathname;if(!active||request.method()!==method||!predicate(path,request))return route.continue();active=false;try{const response=await route.fetch(),body=await response.json();fetched.resolve({status:response.status(),body,request:method==='GET'?null:request.postDataJSON()});await gate.promise;await route.fulfill({response});delivered.resolve();}catch(error){fetched.reject(error);delivered.reject(error);await route.abort().catch(()=>{});}};
  await page.route(pattern,handler);const record={pattern,handler,release:()=>gate.resolve()};held.push(record);if(action)await action();return {ready:()=>bounded(fetched.promise,'Genuine held '+method+' response'),release:async()=>{gate.resolve();await bounded(delivered.promise,'Genuine response delivery');await page.evaluate(()=>new Promise(resolve=>setTimeout(resolve,0)));await page.unroute(pattern,handler);}};
 }
 async function saveVisible(){const pending=page.waitForResponse(response=>response.request().method()==='POST'&&new URL(response.url()).pathname==='/dev/v1/knowledge/proposals');await page.click('#k-save');const response=await pending,body=await response.json(),request=response.request().postDataJSON();await page.waitForFunction(version=>kRecord&&kRecord.version===version&&!kSaving&&!document.getElementById('k-save').disabled,body.version);return {status:response.status(),body,request};}
 async function deleteSource(resource){await openResource(resource);const pending=page.waitForResponse(response=>response.request().method()==='DELETE'&&new URL(response.url()).pathname==='/dev/v1/research/'+resource.id);const confirmation=await native(()=>page.click('#r-delete'));const response=await pending,body=await response.json();await page.waitForFunction(()=>rResource===null&&document.getElementById('r-notice').textContent==='자료와 노트를 삭제했습니다.');return {status:response.status(),body,confirmation};}
 async function download(){const pending=page.waitForEvent('download');await page.click('#k-download');const result=await bounded(pending,'Authentic Knowledge download'),stream=await result.createReadStream();if(!stream)throw Error('Genuine download stream unavailable');const chunks=[];for await(const chunk of stream)chunks.push(chunk);const bytes=Buffer.concat(chunks);return {bytes,text:bytes.toString('utf8'),filename:result.suggestedFilename()};}
 try{
  await page.reload();if(!(await page.evaluate(()=>Boolean(sessionStorage.getItem('lol-coach-dev-token'))))){await page.fill('#token',token);await page.click('#login-form button');}
  await page.waitForFunction(()=>!document.getElementById('workspace').hidden&&document.getElementById('notice').textContent.startsWith('연결됐습니다.'));
  const sourceA=await source('original-A',false),sourceB=await source('independent-B');
  await openResource(sourceA,0);await showKnowledge();await fillRule(initialRule);const beforeGateWrites=writes.length;
  await page.click('#k-use-note');const blockedNoteState=await state();await page.click('#k-save');const blockedSaveState=await state(),beforeList=await api('/knowledge/proposals');
  check('knowledge-unsaved-source-note-gate-no-browser-post',blockedNoteState.source===null&&blockedNoteState.notice.includes('먼저 저장')&&blockedSaveState.source===null&&blockedSaveState.notice.includes('출처로 연결')&&writes.length===beforeGateWrites&&beforeList.status===200,{actual_browser_post_delta:writes.length-beforeGateWrites,unsaved_note_revision:0,source_unset:blockedSaveState.source===null,visible_source_gate:blockedSaveState.notice});
  await showResearch();for(const field of Object.keys(note))await page.fill('#r-'+field,note[field]);await page.click('#r-save');await page.waitForFunction(()=>rNote&&rNote.revision===1&&!rDirty&&!document.getElementById('r-save').disabled);await showKnowledge();await page.click('#k-use-note');
  const createHeld=await hold('POST',path=>path==='/dev/v1/knowledge/proposals',()=>page.click('#k-save')),created=await createHeld.ready();
  const newerRule={...initialRule,claim:'저장 대기 중 새 초안 👀\nB 출처 유지'};const sourceSwitch=await useSource(sourceB);await page.fill('#k-claim',newerRule.claim);const draftDuringCreate=await state();
  await createHeld.release();await page.waitForFunction(version=>kRecord&&kRecord.version===version&&!kSaving,created.body.version);const acknowledged=await state(),actualSaved1=await api(exact(created.body)),actualSourceA=await api('/research/'+sourceA.id);
  const expectedRef={...sourceRef(sourceA),kind:'RAW_DIAGNOSTIC',report_sha256:hash(Buffer.from(canonical(actualSourceA.body.report))),note_sha256:hash(Buffer.from(canonical(note)))};
  check('knowledge-real-create-exploratory-unicode-source-hashes-keeps-new-draft',created.status===201&&equal(created.request.rule,initialRule)&&equal(created.body.source_refs,[expectedRef])&&created.body.review_state==='EXPLORATORY'&&created.body.coaching_enabled===false&&created.body.supersedes===null&&/^[a-f0-9]{32}$/.test(created.body.rule_id)&&/^[a-f0-9]{32}$/.test(created.body.version)&&equal(actualSaved1.body,created.body)&&equal(acknowledged.values,draftDuringCreate.values)&&equal(acknowledged.source,sourceRef(sourceB))&&acknowledged.dirty&&acknowledged.latest===created.body.version&&sourceSwitch.type==='confirm'&&!JSON.stringify(created.body).includes('PRIVATE-SAVED-NOTE-'),{actual_status:created.status,review_state:created.body.review_state,coaching_enabled:created.body.coaching_enabled,exact_unicode_payload:equal(created.request.rule,initialRule),exact_saved_source_hashes:equal(created.body.source_refs,[expectedRef]),new_draft_and_source_retained:equal(acknowledged.values,draftDuringCreate.values)&&equal(acknowledged.source,sourceRef(sourceB)),saved_note_text_not_copied:!JSON.stringify(created.body).includes('PRIVATE-SAVED-NOTE-'),native_source_confirmation:sourceSwitch});
  const second=await saveVisible(),originalUnchanged=await api(exact(created.body));
  check('knowledge-next-save-uses-acknowledged-cas-and-preserves-prior-version',second.status===201&&second.request.rule_id===created.body.rule_id&&second.request.expected_version===created.body.version&&equal(second.request.rule,newerRule)&&equal(second.request.source,sourceRef(sourceB))&&second.body.supersedes===created.body.version&&equal(originalUnchanged.body,created.body)&&!(await state()).dirty,{actual_expected_version:second.request.expected_version,actual_supersedes:second.body.supersedes,old_version_immutable:equal(originalUnchanged.body,created.body),new_draft_exactly_saved:equal(second.request.rule,newerRule)});
  await openProposal(created.body);await page.fill('#k-claim','미저장 다운로드 제외 초안');const beforeDownload=await state(),downloaded=await download();
  check('knowledge-old-version-authentic-download-exact-saved-object',beforeDownload.latest===second.body.version&&equal(beforeDownload.record,created.body)&&downloaded.text===JSON.stringify(created.body,null,2)&&equal(JSON.parse(downloaded.text),created.body)&&equal(await state(),beforeDownload),{latest_cas_for_old_view:beforeDownload.latest,genuine_download_filename:downloaded.filename,downloaded_utf8_sha256:hash(downloaded.bytes),exact_saved_download_bytes:downloaded.text===JSON.stringify(created.body,null,2),dirty_editor_untouched:equal(await state(),beforeDownload)});
  const externalThird=await propose(sourceB,{...initialRule,claim:'외부 경로 실제 v3'},second.body);await page.fill('#k-claim','현재 충돌 후 보존할 초안 😀');const conflictBefore=await state(),conflictPending=page.waitForResponse(response=>response.request().method()==='POST'&&new URL(response.url()).pathname==='/dev/v1/knowledge/proposals');await page.click('#k-save');const conflictResponse=await conflictPending,conflictBody=await conflictResponse.json(),conflictRequest=conflictResponse.request().postDataJSON();await page.waitForFunction(()=>document.getElementById('k-notice').textContent.includes('REVISION_CONFLICT')&&!document.getElementById('k-save').disabled);const conflictAfter=await state(),externalLatest=await api('/knowledge/proposals/'+created.body.rule_id);
  check('knowledge-current-real-conflict-keeps-draft-source-and-auth',conflictResponse.status()===409&&conflictBody.error_code==='REVISION_CONFLICT'&&conflictRequest.expected_version===second.body.version&&equal(conflictAfter.values,conflictBefore.values)&&equal(conflictAfter.source,conflictBefore.source)&&equal(conflictAfter.record,conflictBefore.record)&&conflictAfter.dirty&&!conflictAfter.save_disabled&&conflictAfter.authenticated&&!conflictAfter.workspace_hidden&&externalLatest.body.version===externalThird.version,{actual_status:conflictResponse.status(),actual_error_code:conflictBody.error_code,submitted_expected_version:conflictRequest.expected_version,exact_current_draft_retained:equal(conflictAfter.values,conflictBefore.values),source_retained:equal(conflictAfter.source,conflictBefore.source),authenticated:conflictAfter.authenticated,backend_latest_version:externalLatest.body.version});
  const cancellationBefore=await state(),newCancel=await native(()=>page.click('#k-new'),'dismiss'),oldCancel=await native(()=>page.click('#k-list button[data-rule-id="'+second.body.rule_id+'"][data-version-id="'+second.body.version+'"]'),'dismiss'),sourceCancel=await native(()=>page.click('#k-use-note'),'dismiss');await showResearch();await showKnowledge();const cancellationAfter=await state();
  check('knowledge-native-dirty-navigation-cancel-and-hidden-draft-preserved',[newCancel,oldCancel,sourceCancel].every(dialog=>dialog.type==='confirm'&&dialog.response==='dismiss')&&equal(cancellationAfter,cancellationBefore),{native_confirmations:[newCancel,oldCancel,sourceCancel],exact_hidden_and_cancelled_draft_retained:equal(cancellationAfter,cancellationBefore)});
  const independent=await propose(sourceB,{...initialRule,claim:'독립 생존 후보 '+unique}),cascade=await deleteSource(sourceA);await page.waitForFunction(()=>kRecord===null&&kSource===null&&document.getElementById('k-claim').value===''&&document.getElementById('k-download').disabled);const removed=await Promise.all([created.body,second.body,externalThird].map(row=>api(exact(row)))),survivingIndependent=await api(exact(independent)),cascadeState=await state();
  check('knowledge-source-delete-cascades-descendants-keeps-independent-nonidentifying-receipt',cascade.status===200&&cascade.confirmation.type==='confirm'&&cascade.body.deleted_versions===3&&equal(Object.keys(cascade.body).sort(),['deleted_versions','id','receipt_id','status'])&&/^[a-f0-9]{32}$/.test(cascade.body.receipt_id)&&removed.every(row=>row.status===404)&&survivingIndependent.status===200&&equal(survivingIndependent.body,independent)&&cascadeState.record===null&&cascadeState.source===null&&cascadeState.values.claim===''&&cascadeState.download_disabled&&!JSON.stringify(cascade.body).includes(initialRule.claim)&&!JSON.stringify(cascade.body).includes(note.known),{actual_delete_status:cascade.status,actual_deleted_versions:cascade.body.deleted_versions,receipt_keys:Object.keys(cascade.body).sort(),dependent_get_statuses:removed.map(row=>row.status),independent_get_status:survivingIndependent.status,deleted_display_cleared:cascadeState.record===null&&cascadeState.values.claim===''});
  await openProposal(independent);await page.fill('#k-claim','독립 후보의 미저장 초안 보존');const unrelatedBefore=await state(),unrelated=await source('unrelated-deleted'),unrelatedDeletion=await deleteSource(unrelated);await showKnowledge();await page.waitForSelector('#k-list button[data-version-id="'+independent.version+'"]');await page.waitForFunction(version=>kRecord&&kRecord.version===version&&!document.getElementById('k-download').disabled,independent.version);const unrelatedAfter=await state();
  check('knowledge-unrelated-source-deletion-keeps-independent-dirty-draft',unrelatedDeletion.status===200&&!(unrelatedDeletion.body.deleted_versions>0)&&equal(unrelatedAfter,unrelatedBefore)&&(await api(exact(independent))).status===200,{actual_delete_status:unrelatedDeletion.status,deleted_knowledge_versions:unrelatedDeletion.body.deleted_versions||0,exact_independent_editor_source_notice_auth_retained:equal(unrelatedAfter,unrelatedBefore)});
  const independentSecond=await propose(sourceB,{...initialRule,claim:'독립 후보 외부 v2'},independent),lateError=await hold('POST',path=>path==='/dev/v1/knowledge/proposals',()=>page.click('#k-save')),oldError=await lateError.ready();await newProposal();await page.fill('#k-claim','오래된 오류가 바꾸면 안 되는 새 초안');const newBefore=await state();await lateError.release();const newAfter=await state();
  check('knowledge-old-real-conflict-cannot-follow-new-editor-context',oldError.status===409&&oldError.body.error_code==='REVISION_CONFLICT'&&oldError.request.expected_version===independent.version&&equal(newAfter,newBefore)&&newAfter.authenticated&&newAfter.record===null&&newAfter.source===null&&(await api('/knowledge/proposals/'+independent.rule_id)).body.version===independentSecond.version,{held_actual_status:oldError.status,held_actual_error_code:oldError.body.error_code,new_context_exactly_retained:equal(newAfter,newBefore),authenticated:newAfter.authenticated});

  const middle=await chain('middle-cascade');await openResource(middle.s2);await openProposal(middle.c);const middleExact=await hold('GET',path=>path==='/dev/v1'+exact(middle.c));const middleDelete=await deleteSource(middle.s2),heldMissingMiddle=await middleExact.ready(),middlePending=await state();await middleExact.release();await page.waitForFunction(()=>kRecord===null&&document.getElementById('k-claim').value===''&&document.getElementById('k-download').disabled);const middleState=await state(),middleReads=await Promise.all([api(exact(middle.a)),api(exact(middle.b)),api(exact(middle.c)),api('/research/'+middle.s3.id)]);
  check('knowledge-middle-source-delete-clears-displayed-descendant-with-ancestor-surviving',middleDelete.body.deleted_versions===2&&heldMissingMiddle.status===404&&middlePending.download_disabled&&middleReads[0].status===200&&middleReads[1].status===404&&middleReads[2].status===404&&middleReads[3].status===200&&middleState.record===null&&middleState.source===null&&middleState.values.claim===''&&middleState.download_disabled,{actual_deleted_versions:middleDelete.body.deleted_versions,held_exact_missing_status:heldMissingMiddle.status,download_immediately_blocked_while_exact_validation_pending:middlePending.download_disabled,ancestor_middle_descendant_source_statuses:middleReads.map(row=>row.status),deleted_exact_display_and_download_cleared:middleState.record===null&&middleState.values.claim===''&&middleState.download_disabled});
  const rebind=await chain('late-rebind'),newSource=await source('late-rebind-independent');await openResource(rebind.s2);await openProposal(rebind.c);const sourceRead=await hold('GET',path=>path==='/dev/v1/research/'+rebind.s3.id);const rebindDelete=await deleteSource(rebind.s2),heldOldSource=await sourceRead.ready();await useSource(newSource);await page.fill('#k-claim','新 출처 독립 미저장 초안 😀');const reboundBefore=await state();await sourceRead.release();await page.waitForFunction(()=>kRecord===null&&kDirty&&document.getElementById('k-download').disabled);const reboundAfter=await state();
  check('knowledge-late-deletion-read-keeps-new-independent-source-draft',rebindDelete.body.deleted_versions===2&&heldOldSource.status===200&&equal(reboundAfter.values,reboundBefore.values)&&equal(reboundAfter.source,sourceRef(newSource))&&reboundAfter.dirty&&reboundAfter.record===null&&reboundAfter.latest===null&&reboundAfter.download_disabled&&(await api(exact(rebind.a))).status===200&&(await api(exact(rebind.c))).status===404,{held_actual_source_status:heldOldSource.status,new_independent_source_and_draft_retained:equal(reboundAfter.values,reboundBefore.values)&&equal(reboundAfter.source,sourceRef(newSource)),deleted_saved_record_detached:reboundAfter.record===null,dirty:reboundAfter.dirty});
  const cached=await chain('cached-ack');await openProposal(cached.a);await useSource(cached.s3);await page.fill('#k-claim','새 독립 출처에서 직접 작성한 D 초안');await openResource(cached.s2);await showKnowledge();
  const cachedExact=await hold('GET',path=>path.startsWith('/dev/v1/knowledge/proposals/'+cached.a.rule_id+'/versions/')&&!path.endsWith('/'+cached.a.version)&&!path.endsWith('/'+cached.c.version));
  const postPending=page.waitForResponse(response=>response.request().method()==='POST'&&new URL(response.url()).pathname==='/dev/v1/knowledge/proposals');await page.click('#k-save');const cachedPost=await postPending,cachedD=await cachedPost.json(),genuineOldExact=await cachedExact.ready();const independentDraftBefore=await state();const cachedDelete=await deleteSource(cached.s2);await page.waitForFunction(version=>kLatest===version,cached.a.version);await cachedExact.release();await page.waitForFunction(()=>!kSaving&&!document.getElementById('k-save').disabled);const cachedAfter=await state(),cachedDGet=await api(exact(cachedD));
  check('knowledge-cached-exact-ack-cannot-resurrect-deleted-descendant-with-ancestor-selected',cachedPost.status()===201&&cachedD.supersedes===cached.c.version&&genuineOldExact.status===200&&genuineOldExact.body.version===cachedD.version&&cachedDelete.body.deleted_versions===3&&cachedDGet.status===404&&cachedAfter.record.version===cached.a.version&&cachedAfter.latest===cached.a.version&&equal(cachedAfter.values,independentDraftBefore.values)&&equal(cachedAfter.source,sourceRef(cached.s3))&&cachedAfter.dirty&&!JSON.stringify(cachedAfter.record).includes(cachedD.version),{actual_created_status:cachedPost.status(),held_exact_status:genuineOldExact.status,actual_deleted_versions:cachedDelete.body.deleted_versions,deleted_descendant_get_status:cachedDGet.status,retained_saved_ancestor_version:cachedAfter.record.version,postdelete_latest:cachedAfter.latest,independent_manual_draft_retained:equal(cachedAfter.values,independentDraftBefore.values),deleted_version_not_acknowledged:cachedAfter.record.version!==cachedD.version});
  const opening=await chain('cached-open');await openResource(opening.s2);await openProposal(opening.a);const openRead=await hold('GET',path=>path==='/dev/v1'+exact(opening.c),()=>page.click('#k-list button[data-version-id="'+opening.c.version+'"]')),genuineOldOpen=await openRead.ready();const openDelete=await deleteSource(opening.s2);await page.waitForFunction(version=>kLatest===version,opening.a.version);await openRead.release();await page.waitForFunction(()=>!document.getElementById('k-claim').disabled&&document.getElementById('k-notice').textContent.includes('KNOWLEDGE_RULE_NOT_FOUND'));const afterOpen=await state();
  check('knowledge-cached-exact-open-cannot-display-deleted-historical-version',genuineOldOpen.status===200&&genuineOldOpen.body.version===opening.c.version&&openDelete.body.deleted_versions===2&&afterOpen.record.version===opening.a.version&&afterOpen.latest===opening.a.version&&afterOpen.values.claim===opening.a.claim&&(await api(exact(opening.c))).status===404&&!JSON.stringify(afterOpen.record).includes(opening.c.version),{held_actual_exact_status:genuineOldOpen.status,deleted_versions:openDelete.body.deleted_versions,saved_ancestor_retained:afterOpen.record.version===opening.a.version,deleted_historical_download_not_selected:afterOpen.record.version!==opening.c.version,current_revalidation_error_visible:afterOpen.notice});
  const listing=await chain('cached-list');await openResource(listing.s2);await openProposal(listing.a);const listRead=await hold('GET',path=>path==='/dev/v1/knowledge/proposals',()=>page.click('#k-refresh')),genuineOldList=await listRead.ready();const listDelete=await deleteSource(listing.s2);await page.waitForFunction(version=>!document.querySelector('#k-list button[data-version-id="'+version+'"]'),listing.c.version);await listRead.release();const listState=await page.locator('#k-list').innerText(),listBackend=await api('/knowledge/proposals');
  check('knowledge-cached-list-cannot-restore-deleted-version-metadata',genuineOldList.status===200&&genuineOldList.body.some(row=>row.version===listing.c.version)&&listDelete.body.deleted_versions===2&&!listState.includes(listing.c.claim)&&!listState.includes(listing.b.claim)&&!listBackend.body.some(row=>row.version===listing.c.version||row.version===listing.b.version)&&(await state()).record.version===listing.a.version,{held_actual_list_status:genuineOldList.status,held_list_contains_deleted_version:genuineOldList.body.some(row=>row.version===listing.c.version),actual_deleted_versions:listDelete.body.deleted_versions,deleted_claim_metadata_absent:!listState.includes(listing.c.claim)&&!listState.includes(listing.b.claim),actual_backend_deleted_versions_absent:!listBackend.body.some(row=>row.version===listing.c.version||row.version===listing.b.version)});
  const deleting=await chain('proposal-delete-open');await openProposal(deleting.a);
  const proposalPattern='**/dev/v1/knowledge/proposals/'+deleting.a.rule_id,dispatchGate=deferred(),deleteRequested=deferred(),deleteDelivered=deferred(),latestGate=deferred(),latestFetched=deferred(),latestDelivered=deferred();let deleteActive=true,latestActive=true;
  const proposalHandler=async route=>{const request=route.request();try{
   if(request.method()==='DELETE'&&deleteActive){deleteActive=false;const body=request.postDataJSON();deleteRequested.resolve(body);await dispatchGate.promise;const response=await route.fetch(),actual=await response.json();await route.fulfill({response});deleteDelivered.resolve({status:response.status(),body:actual,request:body});}
   else if(request.method()==='GET'&&latestActive){latestActive=false;const response=await route.fetch(),body=await response.json();latestFetched.resolve({status:response.status(),body});await latestGate.promise;await route.fulfill({response});latestDelivered.resolve();}
   else await route.continue();
  }catch(error){deleteRequested.reject(error);deleteDelivered.reject(error);latestFetched.reject(error);latestDelivered.reject(error);await route.abort().catch(()=>{});}};
  await page.route(proposalPattern,proposalHandler);held.push({pattern:proposalPattern,handler:proposalHandler,release:()=>{dispatchGate.resolve();latestGate.resolve();}});
  const proposalConfirmation=await native(()=>page.click('#k-delete')),actualDeleteRequest=await bounded(deleteRequested.promise,'Actual native proposal DELETE request before dispatch');
  await page.click('#k-list button[data-version-id="'+deleting.c.version+'"]');const cachedLatestBeforeDelete=await bounded(latestFetched.promise,'Genuine latest C response before DELETE commit');
  dispatchGate.resolve();const actualProposalDelete=await bounded(deleteDelivered.promise,'Actual backend proposal DELETE commit and delivery');await page.waitForFunction(()=>kRecord===null&&document.getElementById('k-download').disabled);const afterProposalDelete=await state();
  latestGate.resolve();await bounded(latestDelivered.promise,'Genuine old latest C response delivery');await page.evaluate(()=>new Promise(resolve=>setTimeout(resolve,0)));await page.unroute(proposalPattern,proposalHandler);const afterCachedProposalOpen=await state(),deletedProposalReads=await Promise.all([api(exact(deleting.a)),api(exact(deleting.c)),api('/knowledge/proposals/'+deleting.a.rule_id),api('/research/'+deleting.s3.id)]);
  const deletedProposalList=await page.locator('#k-list').innerText();
  check('knowledge-proposal-delete-invalidates-pending-same-rule-historical-open',proposalConfirmation.type==='confirm'&&actualDeleteRequest.expected_version===deleting.c.version&&cachedLatestBeforeDelete.status===200&&cachedLatestBeforeDelete.body.version===deleting.c.version&&actualProposalDelete.status===200&&actualProposalDelete.body.deleted_versions===3&&afterCachedProposalOpen.record===null&&afterCachedProposalOpen.source===null&&afterCachedProposalOpen.values.claim===''&&afterCachedProposalOpen.download_disabled&&equal(afterCachedProposalOpen,afterProposalDelete)&&equal(deletedProposalReads.map(row=>row.status),[404,404,404,200])&&![deleting.a,deleting.b,deleting.c].some(record=>deletedProposalList.includes(record.claim)||deletedProposalList.includes(record.version)),{native_confirmation:proposalConfirmation,actual_delete_expected_version:actualDeleteRequest.expected_version,native_delete_dispatch_gated:true,held_genuine_latest_status:cachedLatestBeforeDelete.status,actual_delete_status:actualProposalDelete.status,actual_deleted_versions:actualProposalDelete.body.deleted_versions,late_deleted_version_not_rendered:afterCachedProposalOpen.record===null&&afterCachedProposalOpen.values.claim==='',deleted_download_blocked:afterCachedProposalOpen.download_disabled,exact_cleared_state_retained:equal(afterCachedProposalOpen,afterProposalDelete),deleted_exact_latest_and_surviving_source_statuses:deletedProposalReads.map(row=>row.status)});
  await newProposal();await useSource(sourceB);await fillRule({...initialRule,claim:'로그아웃 전 요청한 실제 후보'});const logoutHeld=await hold('POST',path=>path==='/dev/v1/knowledge/proposals',()=>page.click('#k-save')),logoutSaved=await logoutHeld.ready();await page.click('#show-synthetic');await page.click('#logout');const logoutBefore=await state();await logoutHeld.release();const logoutAfter=await state(),persistedAfterLogout=await api(exact(logoutSaved.body));
  check('knowledge-genuine-held-create-response-cannot-follow-logout',logoutSaved.status===201&&equal(logoutAfter,logoutBefore)&&!logoutAfter.authenticated&&logoutAfter.workspace_hidden&&logoutAfter.record===null&&logoutAfter.source===null&&logoutAfter.values.claim===''&&logoutAfter.values.author===''&&logoutAfter.download_disabled&&(await page.locator('#k-list').innerText())===''&&persistedAfterLogout.status===200&&persistedAfterLogout.body.review_state==='EXPLORATORY'&&persistedAfterLogout.body.coaching_enabled===false,{held_actual_create_status:logoutSaved.status,exact_logout_state_retained:equal(logoutAfter,logoutBefore),authenticated:logoutAfter.authenticated,workspace_hidden:logoutAfter.workspace_hidden,backend_saved_version_exists:persistedAfterLogout.status===200,review_state:persistedAfterLogout.body.review_state,coaching_enabled:persistedAfterLogout.body.coaching_enabled});
 }finally{for(const route of held)route.release();for(const route of held)await page.unroute(route.pattern,route.handler);page.off('request',track);}
};
